const { SlashCommandBuilder, EmbedBuilder } = require('discord.js');

module.exports = {
    data: new SlashCommandBuilder()
        .setName('joke')
        .setDescription('Get a random joke'),

    async execute(interaction) {
           const jokes = [
    "Why did the coffee file a police report?\nIt got mugged. ☕",
    "What do you call a sleeping dinosaur?\nA dino-snore. 🦕",
    "Why can't you trust stairs?\nThey're always up to something. 🪜",
    "What do you call cheese that isn't yours?\nNacho cheese. 🧀",
    "Why did the invisible man turn down the job offer?\nHe couldn't see himself doing it. 👻",
    "What do you call a bear with no teeth?\nA gummy bear. 🐻",
    "Why did the calendar go to therapy?\nIt had too many dates. 📅",
    "What's a vampire's favorite fruit?\nA blood orange. 🍊",
    "Why do cows wear bells?\nBecause their horns don't work. 🐄",
    "What do you call a fish without eyes?\nA fsh. 🐟",
    "Why did the tomato turn red?\nBecause it saw the salad dressing. 🥗",
    "What do lawyers wear to court?\nLawsuits. 👔",
    "Why did the belt go to jail?\nIt held up a pair of pants. 👖",
    "What do you call a lazy kangaroo?\nA pouch potato. 🦘",
    "Why did the scarecrow become a motivational speaker?\nHe was outstanding in his field. 🌾",
    "What do you call a snowman with a six-pack?\nAn abdominal snowman. ⛄",
    "Why did the bicycle fall asleep?\nIt was two-tired. 😴",
    "What do you call a pile of cats?\nA meowtain. 🐱",
    "Why did the ocean break up with the pond?\nIt thought he was too shallow. 🌊",
    "What do you call a dog magician?\nA labracadabrador. 🐶",
    "Why don't oysters share?\nBecause they're shellfish. 🦪",
    "What do you call a grumpy sheep?\nA baaaad mood. 🐑",
    "Why did the shoe go to school?\nTo get some sole. 👟",
    "What do you call an alligator in a vest?\nAn investi-gator. 🐊",
    "Why did the banana go to the doctor?\nIt wasn't peeling well. 🍌",
    "What do you call a sad strawberry?\nA blueberry. 🫐",
    "Why did the moon skip dinner?\nIt was full. 🌕",
    "What do you call a cow that plays guitar?\nA moo-sician. 🎸",
    "Why did the clock get kicked out of class?\nIt tocked too much. 🕰️",
    "What do you call a fake noodle?\nAn impasta. 🍝",
    "Why did the pillow go to therapy?\nIt was stuffed with feelings. 🛏️",
    "What do you call a dinosaur that crashes their car?\nTyrannosaurus wrecks. 🦖",
    "Why did the grape stop in the middle of the road?\nIt ran out of juice. 🍇",
    "What do you call a pig that does karate?\nA pork chop. 🥋",
    "Why don't mountains get cold?\nThey wear snowcaps. 🏔️",
    "What do you call a lazy pebble?\nA rolling stone that stopped. 🪨",
    "Why did the scarecrow get a promotion?\nHe was outstanding in every field. 🌾",
    "What do you call a penguin in the desert?\nLost. 🐧",
    "Why did the broom get a raise?\nIt swept the competition. 🧹",
    "What do you call a sleeping bull?\nA bulldozer. 🐂",
    "Why did the math teacher open a bakery?\nBecause she kneaded the dough. 🥐",
    "What do you call a baby potato?\nA small fry. 🍟",
    "Why did the flashlight apply for a job?\nIt wanted to brighten its future. 🔦",
    "What do you call a robot that takes long routes?\nR2-Detour. 🤖",
    "Why did the tree go to the dentist?\nIt needed a root canal. 🌳",
    "What do you call a duck that gets straight A's?\nA wise quacker. 🦆",
    "Why did the lamp fail the test?\nIt wasn't very bright. 💡",
    "What do you call a nervous javelin thrower?\nShakespeare. 🎭",
    "Why did the tomato blush at the fridge?\nIt saw the salad dressing… again. 🥗",
    "What do you call a man who can't stop buying carpets?\nRugged. 🪵",
    "Why did the scarecrow win a Nobel prize?\nHe was outstanding in his field — again. 🏆",
    "What do you call a boomerang that doesn't come back?\nA stick. 🪃",
    "Why did the stadium get so hot after the game?\nAll the fans left. 🏟️",
    "What do you call a parade of rabbits hopping backwards?\nA receding hare-line. 🐰",
    "Why did the golfer bring an extra shirt?\nIn case he got a hole in one. ⛳",
    "What do you call a factory that makes okay products?\nA satisfactory. 🏭",
    "Why did the computer go to the doctor?\nIt had a virus. 💻",
    "What do you call a bee that can't make up its mind?\nA maybe. 🐝",
    "Why did the kid throw the clock out the window?\nTo see time fly. ⏰",
    "What do you call a hen who counts her eggs?\nA mathemachicken. 🐔",
    "Why did the teddy bear skip dessert?\nShe was already stuffed. 🧸",
    "What do you call a group of musical whales?\nAn orca-stra. 🐋",
    "Why did the scarecrow refuse to fight?\nHe didn't have the guts. 💀",
    "What do you call a map that sings?\nA road tune. 🗺️",
    "Why did the toilet paper roll downhill?\nTo get to the bottom. 🧻",
    "What do you call a ghosts's favorite dessert?\nI scream. 👻",
    "Why did the music teacher need a ladder?\nTo reach the high notes. 🎵",
    "What do you call a man with no nose?\nNobody knows. 👃",
    "Why did the cookie cry?\nBecause his mom was a wafer so long. 🍪",
    "What do you call a dinosaur that's always on time?\nPronto-saurus. ⏱️",
    "Why did the picture go to prison?\nBecause it was framed. 🖼️",
    "What do you call a cold dog?\nA chilly dog. 🐕",
    "Why did the banana wear sunscreen?\nBecause it didn't want to peel. 🌞",
    "What do you call a snail on a ship?\nA snailor. 🐌",
    "Why did the gardener win an award?\nBecause he was really good at his roots. 🌱",
    "What do you call a shoe made of a banana?\nA slipper. 🍌",
    "Why did the scarecrow enter politics?\nHe was great at making empty promises. 🗳️",
    "What do you call a knight who's afraid of the dark?\nSir Render. 🛡️",
    "Why did the electrician get shocked?\nHe didn't know his limits. ⚡",
    "What do you call a comedian potato?\nA laughing stock. 🥔",
    "Why did the soap opera actor win an award?\nBecause he always cleaned up. 🧼",
    "What do you call a snowboard made of pasta?\nA slippery slope. 🏂",
    "Why did the egg hide?\nIt was a little chicken. 🐣",
    "What do you call a cow in an earthquake?\nA milkshake. 🥛",
    "Why did the library break up with the bookstore?\nToo many issues. 📚",
    "What do you call a train full of toffee?\nA chew-chew train. 🚂",
    "Why did the cat sit on the computer?\nTo keep an eye on the mouse. 🖱️",
    "What do you call a sleeping T-Rex?\nA dino-snore. 😴",
    "Why did the weather forecaster bring a ladder?\nBecause the forecast called for high pressure. 🌦️",
    "What do you call an elephant that doesn't matter?\nIrrelevant. 🐘",
    "Why did the ocean blush?\nBecause the seaweed. 🌊",
    "What do you call a line of rabbits walking backwards?\nA receding hare. 🐇",
    "Why did the lemon stop rolling downhill?\nIt ran out of juice. 🍋",
    "What do you call a belt made of watches?\nA waist of time. ⌚",
    "Why did the skeleton go to the party alone?\nBecause he had no body to go with. 💀",
    "What do you call a ship that eats candy?\nA Lollipop. 🍭",
    "Why did the pilot sit on a wet chair?\nHe wanted to fly by the seat of his pants. ✈️",
    "What do you call two birds in love?\nTweethearts. 🐦",
];

        const randomJoke = jokes[Math.floor(Math.random() * jokes.length)];

        const embed = new EmbedBuilder()
            .setColor(0xffcc00)
            .setTitle('🤡 Random Joke')
            .setDescription(randomJoke)
            .setFooter({ text: 'Use /joke for another one!' });

        await interaction.reply({ embeds: [embed] });
    }
};